ALTER TABLE glkeit00_AUFGABEN ADD CONSTRAINT SWS_AUFGABEN_NOT_NEGATIVE CHECK (AUFGABENSWS > 0)
^

ALTER TABLE glkeit00_MODUL_SPO ADD CONSTRAINT FACHSEMESTER CHECK (SEMESTER IN ('1', '2', '3', '4', '5', '6', '7'))
^

ALTER TABLE glkeit00_MODUL_SPO ADD CONSTRAINT SWS_MODUL_NOT_NEGATIVE CHECK (SWS > 0)
^

ALTER TABLE glkeit00_ZEITSEMESTER ADD CONSTRAINT ZEITSEMESTER_C CHECK 
(
	(ZEITSEMESTERID like 'SS__' OR ZEITSEMESTERID LIKE 'WS__') 
	AND
		(  ZEITSEMESTERID LIKE '__0_' 
		OR ZEITSEMESTERID LIKE '__1_' 
		OR ZEITSEMESTERID LIKE '__2_' 
		OR ZEITSEMESTERID LIKE '__3_' 
		OR ZEITSEMESTERID LIKE '__4_' 
		OR ZEITSEMESTERID LIKE '__5_'
		OR ZEITSEMESTERID LIKE '__6_'
	 	OR ZEITSEMESTERID LIKE '__7_' 	
		OR ZEITSEMESTERID LIKE '__8_' 
		OR ZEITSEMESTERID LIKE '__9_')
	AND 
		(  ZEITSEMESTERID LIKE '___0' 
		OR ZEITSEMESTERID LIKE '___1'	
		OR ZEITSEMESTERID LIKE '___2' 
		OR ZEITSEMESTERID LIKE '___3'
		OR ZEITSEMESTERID LIKE '___4' 
		OR ZEITSEMESTERID LIKE '___5'	
		OR ZEITSEMESTERID LIKE '___6'
		OR ZEITSEMESTERID LIKE '___7'
		OR ZEITSEMESTERID LIKE '___8' 
		OR ZEITSEMESTERID LIKE '___9')
)
^

ALTER TABLE glkeit00_PROF_ZEITSEMESTER ADD CONSTRAINT DEPUTAT_NOT_TOO_LOW CHECK (DEPUTAT >= 9)
^
