ALTER TABLE glkeit00_AUFGABEN ADD CONSTRAINT SWS_AUFGABEN_NOT_NEGATIVE CHECK (AUFGABENSWS > 0)
^

ALTER TABLE glkeit00_MODUL_SPO ADD CONSTRAINT FACHSEMESTER CHECK (SEMESTER IN ('1', '2', '3', '4', '5', '6', '7'))
^

ALTER TABLE glkeit00_MODUL_SPO ADD CONSTRAINT SWS_MODUL_NOT_NEGATIVE CHECK (SWS > 0)
^

--ALTER TABLE glkeit00_ZEITSEMESTER ADD CONSTRAINT ZEITSEMESTER_CHECK CHECK (ZEITSEMESTERID like '[SW]S[0-9]{2}')^

ALTER TABLE glkeit00_ZEITSEMESTER ADD CONSTRAINT ZEITSEMESTER_CHECK CHECK (ZEITSEMESTERID IN ('SS11','WS11', 'SS12','WS12', 'SS13','WS13', 'SS14','WS14', 'SS15','WS15', 'SS16', 'WS16'))^