--#SET TERMINATOR %

CONNECT TO LABOR%
CREATE TRIGGER STUDENT.TRG_DEPUTAT NO CASCADE BEFORE  INSERT  ON STUDENT.GLKEIT00_PROF_ZEITSEMESTER 
	REFERENCING  NEW AS n  FOR EACH ROW  MODE DB2SQL 
WHEN ( n.deputat < 0 )
BEGIN ATOMIC
set n.deputat = 0 ;
END%
CONNECT RESET%


CONNECT TO LABOR%
CREATE TRIGGER STUDENT.TRG_UPD_DEPUTAT NO CASCADE BEFORE UPDATE 
OF DEPUTAT ON STUDENT.GLKEIT00_PROF_ZEITSEMESTER  
REFERENCING  OLD AS o  NEW AS n  FOR EACH ROW  MODE DB2SQL 
WHEN ( n.deputat < 0 )
BEGIN ATOMIC
set n.deputat = 0 ;
END%

CONNECT RESET%

--SET TERMINATOR;
