insert into STUDENT.GLKEIT00_ZEITSEMESTER (ZEITSEMESTERID)
values
('SS11'),
('WS11'),
('SS12'),
('WS12')
^

INSERT INTO GLKEIT00_FAKULTAET
SELECT Fakultaet
FROM TD_DOZENTEN as td
WHERE td.Fakultaet is not NULL
GROUP by td.Fakultaet
^

INSERT INTO GLKEIT00_DOZENT
SELECT PRUEFERNUMMER, DOZENT, NULL, Fakultaet
FROM TD_DOZENTEN as td
WHERE td.Typ1 is not NULL
^

INSERT INTO STUDENT.GLKEIT00_PROF
SELECT PRUEFERNUMMER, DOZENT, TO_DATE(Typ1_Seit, 'DD.MM.YYYY')
From
(
        SELECT PRUEFERNUMMER, DOZENT, Typ1, Typ1_Seit
        FROM STUDENT.TD_DOZENTEN as td_doz
	WHERE ((td_doz.Typ1 = 'P' and td_doz.Typ2 is NULL) or (td_doz.Typ1 = 'P' and td_doz.Typ2 = 'LB'))
)
^

INSERT INTO STUDENT.GLKEIT00_PROF
SELECT PRUEFERNUMMER, DOZENT, TO_DATE(Typ2_Seit, 'DD.MM.YYYY')
From
(
        SELECT PRUEFERNUMMER, DOZENT, Typ2, Typ2_Seit
        FROM STUDENT.TD_DOZENTEN as td_doz
	WHERE ( td_doz.Typ1 = 'LB' and td_doz.Typ2 = 'P' )
)
^

INSERT INTO STUDENT.GLKEIT00_LB
SELECT PRUEFERNUMMER, 'SS11', DOZENT, TO_DATE(Typ1_Seit, 'DD.MM.YYYY')
From
(
        SELECT PRUEFERNUMMER, DOZENT, Typ1, Typ2, Typ1_Seit
        FROM STUDENT.TD_DOZENTEN as td_doz
        WHERE ((td_doz.Typ1 = 'LB' and td_doz.Typ2 is NULL) or (td_doz.Typ1 = 'LB' and td_doz.Typ2 = 'P'))
)
^

INSERT INTO STUDENT.GLKEIT00_LB
SELECT PRUEFERNUMMER, 'SS11', DOZENT, TO_DATE(Typ2_Seit, 'DD.MM.YYYY')
From
(
        SELECT PRUEFERNUMMER, DOZENT, Typ2, Typ2_Seit
        FROM STUDENT.TD_DOZENTEN as td_doz
	WHERE ( td_doz.Typ1 = 'P' and td_doz.Typ2 = 'LB' )
)
^

INSERT INTO GLKEIT00_PROF_ZEITSEMESTER
SELECT DEPUTAT_SS11, PRUEFERNUMMER, 'SS11', DOZENT
FROM
(
SELECT PRUEFERNUMMER, DOZENT, DEPUTAT_SS11, DEPUTAT_WS11
FROM TD_DOZENTEN as td
JOIN GLKEIT00_PROF p ON td.PRUEFERNUMMER = p.DOZENTID and td.DOZENT = p.LASTNAME
WHERE (td.DEPUTAT_SS11 is not NULL)
)
^


INSERT INTO GLKEIT00_PROF_ZEITSEMESTER
SELECT DEPUTAT_WS11, PRUEFERNUMMER, 'WS11', DOZENT
FROM
(
SELECT PRUEFERNUMMER, DOZENT, DEPUTAT_SS11, DEPUTAT_WS11
FROM TD_DOZENTEN as td
JOIN GLKEIT00_PROF p ON td.PRUEFERNUMMER = p.DOZENTID and td.DOZENT = p.LASTNAME
WHERE (td.DEPUTAT_WS11 is not NULL)
)
^

INSERT INTO GLKEIT00_SPO
SELECT Studiengang, 'IT'
FROM TD_SPO
GROUP BY Studiengang
^


INSERT INTO GLKEIT00_MODUL (ModulID, Teilgebiet, Modultitel)
	SELECT NEXT VALUE FOR GLKEIT00_MODUL_SEQ, Teilgebiet, Modulname
FROM TD_SPO as s
WHERE Teilgebiet is not null
GROUP by Teilgebiet, Modulname
^

INSERT INTO GLKEIT00_MODUL (ModulID, Teilgebiet, Modultitel)
SELECT NEXT VALUE FOR GLKEIT00_MODUL_SEQ, S.FACH, S.FACH
FROM TD_STDPL AS S
WHERE NOT EXISTS ( SELECT TEILGEBIET FROM GLKEIT00_MODUL AS M WHERE S.FACH = M.TEILGEBIET )
GROUP by S.FACH
^








INSERT INTO GLKEIT00_MODUL_SPO
	SELECT Modulnr, Teilgebiet, Studiengang, Semester, Credits
FROM TD_SPO
^

INSERT INTO GLKEIT00_VERANSTALTUNG
SELECT DISTINCT Nr, akadHJ, Fach, Studiengang
FROM TD_STDPL
^



--INSERT INTO GLKEIT00_VERANSTALTUNG

SELECT DISTINCT Nr, akadHJ, Fach, Studiengang
FROM TD_STDPL
WHERE EXISTS (SELECT Teilgebiet FROM GLKEIT00_MODUL_SPO WHERE TD_STDPL.Fach = GLKEIT00_MODUL_SPO.Teilgebiet)
^

SELECT *
FROM TD_STDPL as t1
WHERE NOT EXISTS 
(
	SELECT Teilgebiet from GLKEIT00_MODUL_SPO as t2
	WHERE t1.Fach = t2.Teilgebiet
)
^

SELECT Fach
FROM TD_STDPL as t1
INNER JOIN GLKEIT00_MODUL_SPO as t2
ON t1.Fach = t2.Teilgebiet^



